"""employee accounts and requests

Revision ID: 92df479d5f4b
Revises: 3112a4bb08ea
Create Date: 2026-08-24 19:03:23.348944
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92df479d5f4b'
down_revision: Union[str, None] = '3112a4bb08ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('need', 'broken', 'pickup', 'other', name='requestkind', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'done', 'rejected', name='requeststatus', native_enum=False, length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], name=op.f('fk_requests_closed_by_user_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_requests_employee_id_employees')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_requests_item_id_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_employee_id'), ['employee_id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_employee_id_employees'), 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_employee_id_employees'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_users_employee_id'), type_='unique')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_status'))
        batch_op.drop_index(batch_op.f('ix_requests_employee_id'))

    op.drop_table('requests')
    # ### end Alembic commands ###
