"""handover acknowledgement

Revision ID: 3112a4bb08ea
Revises: afeccf1fcc51
Create Date: 2026-08-02 14:14:49.398529
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3112a4bb08ea'
down_revision: Union[str, None] = 'afeccf1fcc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('acknowledged_by_employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_movements_acknowledged_by_employee_id_employees'), 'employees', ['acknowledged_by_employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_movements_acknowledged_by_employee_id_employees'), type_='foreignkey')
        batch_op.drop_column('acknowledged_by_employee_id')
        batch_op.drop_column('acknowledged_at')

    # ### end Alembic commands ###
