"""initial schema

Revision ID: fa704cd23759
Revises: 
Create Date: 2026-07-31 16:53:18.933517
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fa704cd23759'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('item_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_container', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('suggested_attributes', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('number_sequences',
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prefix')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('storage_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('cabinet', 'shelf', 'cell', 'room', name='storageplacekind', native_enum=False, length=24), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['storage_places.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='userrole', native_enum=False, length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.String(length=24), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('default_room_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_full_name'), ['full_name'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inv_number', sa.String(length=16), nullable=False),
    sa.Column('legacy_number', sa.String(length=32), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('in_use', 'reserve', 'incomplete', 'donor', 'repair', 'written_off', name='itemstatus', native_enum=False, length=24), nullable=False),
    sa.Column('condition_note', sa.Text(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('auto_data', sa.JSON(), nullable=True),
    sa.Column('loc_kind', sa.Enum('inside', 'storage', 'person', 'room', 'external', 'written_off', name='locationkind', native_enum=False, length=24), nullable=False),
    sa.Column('loc_parent_item_id', sa.Integer(), nullable=True),
    sa.Column('loc_storage_place_id', sa.Integer(), nullable=True),
    sa.Column('loc_employee_id', sa.Integer(), nullable=True),
    sa.Column('loc_room_id', sa.Integer(), nullable=True),
    sa.Column('loc_external_note', sa.String(length=200), nullable=True),
    sa.Column('loc_since', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("\n(loc_kind = 'inside'\n    AND loc_parent_item_id IS NOT NULL AND loc_storage_place_id IS NULL\n    AND loc_employee_id IS NULL AND loc_room_id IS NULL AND loc_external_note IS NULL)\nOR (loc_kind = 'storage'\n    AND loc_parent_item_id IS NULL AND loc_storage_place_id IS NOT NULL\n    AND loc_employee_id IS NULL AND loc_room_id IS NULL AND loc_external_note IS NULL)\nOR (loc_kind = 'person'\n    AND loc_parent_item_id IS NULL AND loc_storage_place_id IS NULL\n    AND loc_employee_id IS NOT NULL AND loc_external_note IS NULL)\nOR (loc_kind = 'room'\n    AND loc_parent_item_id IS NULL AND loc_storage_place_id IS NULL\n    AND loc_employee_id IS NULL AND loc_room_id IS NOT NULL AND loc_external_note IS NULL)\nOR (loc_kind = 'external'\n    AND loc_parent_item_id IS NULL AND loc_storage_place_id IS NULL\n    AND loc_employee_id IS NULL AND loc_room_id IS NULL AND loc_external_note IS NOT NULL)\nOR (loc_kind = 'written_off'\n    AND loc_parent_item_id IS NULL AND loc_storage_place_id IS NULL\n    AND loc_employee_id IS NULL AND loc_room_id IS NULL AND loc_external_note IS NULL)\n", name='ck_items_location_shape'),
    sa.CheckConstraint('loc_parent_item_id IS NULL OR loc_parent_item_id <> id', name='ck_items_not_inside_itself'),
    sa.ForeignKeyConstraint(['loc_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['loc_parent_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['loc_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['loc_storage_place_id'], ['storage_places.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['item_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_inv_number'), ['inv_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_legacy_number'), ['legacy_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_loc_employee_id'), ['loc_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_loc_kind'), ['loc_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_loc_parent_item_id'), ['loc_parent_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_loc_room_id'), ['loc_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_loc_storage_place_id'), ['loc_storage_place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_status'), ['status'], unique=False)

    op.create_table('item_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'key', name='uq_item_attribute_key')
    )
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('moved_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Enum('register', 'issue', 'return', 'install', 'uninstall', 'to_storage', 'transfer_out', 'repair', 'write_off', name='movementreason', native_enum=False, length=24), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('moved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_employee_id', sa.Integer(), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('from_kind', sa.Enum('inside', 'storage', 'person', 'room', 'external', 'written_off', name='locationkind', native_enum=False, length=24), nullable=True),
    sa.Column('from_parent_item_id', sa.Integer(), nullable=True),
    sa.Column('from_storage_place_id', sa.Integer(), nullable=True),
    sa.Column('from_employee_id', sa.Integer(), nullable=True),
    sa.Column('from_room_id', sa.Integer(), nullable=True),
    sa.Column('from_external_note', sa.String(length=200), nullable=True),
    sa.Column('from_label', sa.String(length=300), nullable=False),
    sa.Column('to_kind', sa.Enum('inside', 'storage', 'person', 'room', 'external', 'written_off', name='locationkind', native_enum=False, length=24), nullable=False),
    sa.Column('to_parent_item_id', sa.Integer(), nullable=True),
    sa.Column('to_storage_place_id', sa.Integer(), nullable=True),
    sa.Column('to_employee_id', sa.Integer(), nullable=True),
    sa.Column('to_room_id', sa.Integer(), nullable=True),
    sa.Column('to_external_note', sa.String(length=200), nullable=True),
    sa.Column('to_label', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['from_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['from_parent_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['from_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['from_storage_place_id'], ['storage_places.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['to_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['to_parent_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['to_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['to_storage_place_id'], ['storage_places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movements_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_moved_at'), ['moved_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movements_moved_at'))
        batch_op.drop_index(batch_op.f('ix_movements_item_id'))

    op.drop_table('movements')
    op.drop_table('item_attributes')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_status'))
        batch_op.drop_index(batch_op.f('ix_items_serial_number'))
        batch_op.drop_index(batch_op.f('ix_items_loc_storage_place_id'))
        batch_op.drop_index(batch_op.f('ix_items_loc_room_id'))
        batch_op.drop_index(batch_op.f('ix_items_loc_parent_item_id'))
        batch_op.drop_index(batch_op.f('ix_items_loc_kind'))
        batch_op.drop_index(batch_op.f('ix_items_loc_employee_id'))
        batch_op.drop_index(batch_op.f('ix_items_legacy_number'))
        batch_op.drop_index(batch_op.f('ix_items_inv_number'))

    op.drop_table('items')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_full_name'))

    op.drop_table('employees')
    op.drop_table('users')
    op.drop_table('storage_places')
    op.drop_table('rooms')
    op.drop_table('number_sequences')
    op.drop_table('item_types')
    op.drop_table('departments')
    # ### end Alembic commands ###
