"""consumable stock

Revision ID: 859834afb8ef
Revises: 92df479d5f4b
Create Date: 2026-08-24 19:25:27.033917
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '859834afb8ef'
down_revision: Union[str, None] = '92df479d5f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumable_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('storage_place_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['storage_place_id'], ['storage_places.id'], name=op.f('fk_consumable_stock_storage_place_id_storage_places')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumable_stock'))
    )
    with op.batch_alter_table('consumable_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumable_stock_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_stock_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_stock_storage_place_id'), ['storage_place_id'], unique=False)

    op.create_table('consumable_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('happened_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Enum('receipt', 'issue', 'adjust', name='consumablereason', native_enum=False, length=24), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('moved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_consumable_movements_employee_id_employees')),
    sa.ForeignKeyConstraint(['moved_by_user_id'], ['users.id'], name=op.f('fk_consumable_movements_moved_by_user_id_users')),
    sa.ForeignKeyConstraint(['stock_id'], ['consumable_stock.id'], name=op.f('fk_consumable_movements_stock_id_consumable_stock'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumable_movements'))
    )
    with op.batch_alter_table('consumable_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumable_movements_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_movements_happened_at'), ['happened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumable_movements_stock_id'), ['stock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumable_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumable_movements_stock_id'))
        batch_op.drop_index(batch_op.f('ix_consumable_movements_happened_at'))
        batch_op.drop_index(batch_op.f('ix_consumable_movements_employee_id'))

    op.drop_table('consumable_movements')
    with op.batch_alter_table('consumable_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumable_stock_storage_place_id'))
        batch_op.drop_index(batch_op.f('ix_consumable_stock_name'))
        batch_op.drop_index(batch_op.f('ix_consumable_stock_category'))

    op.drop_table('consumable_stock')
    # ### end Alembic commands ###
